[package]
name = "derive_debug"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["extra-traits", "visit"] }
